# Generated by Django 5.2.14 on 2026-08-08 22:18

import cloudinary_storage.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DubbingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                        upload_to="dubbing/input/",
                    ),
                ),
                (
                    "output_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                        upload_to="dubbing/output/",
                    ),
                ),
                ("percentage", models.FloatField(default=0.0)),
                ("current_step", models.IntegerField(default=0)),
                (
                    "status_text",
                    models.CharField(default="Waiting in queue...", max_length=255),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
