# Generated by Django 5.2.14 on 2026-08-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dubbingjob",
            name="output_video",
            field=models.FileField(blank=True, null=True, upload_to="dubbing/output/"),
        ),
        migrations.AlterField(
            model_name="dubbingjob",
            name="video_file",
            field=models.FileField(upload_to="dubbing/input/"),
        ),
    ]
