# Generated by Django 5.2.14 on 2026-08-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_dubbingjob_output_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dubbingjob",
            name="output_video",
            field=models.FileField(blank=True, null=True, upload_to="outputs/"),
        ),
        migrations.AlterField(
            model_name="dubbingjob",
            name="video_file",
            field=models.FileField(upload_to="uploaded_videos/"),
        ),
    ]
